chestreward:
  - ==: org.bukkit.inventory.ItemStack
    type: WOOD_AXE
  - ==: org.bukkit.inventory.ItemStack
    type: CHEST
  - ==: org.bukkit.inventory.ItemStack
    type: REDSTONE_COMPARATOR
  - ==: org.bukkit.inventory.ItemStack
    type: REDSTONE
  - ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_SWORD
    damage: 1
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        DAMAGE_ALL: 2
        DURABILITY: 2
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    damage: 8232
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
    damage: 16427
chestreward_percentage:
  - 10
  - 100
  - 50
  - 20
  - 25
  - 15
  - 2
scoreboard: true
