name: Koth
main: fr.nessar.Koth
description: KOTH plugin made with hearth.
version: 1
api-version: 1.8.8
depend:
  - WorldEdit
  - Factions
softdepend:
  - PlaceholderAPI
commands:
  koth:
    description: koth base command
    permission: koth.base
    usage: "Usage: /<command> [new | delete | list | start | stop | setchest | save | reloadconfig] <name> <time>"

permissions:
  koth.base:
    description: allow base koth command
    default: op
